In [ ]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.getOrCreate()
worldDF = spark.read.option('inferSchema','true').csv('datasets/world.txt')
worldDF = worldDF.withColumnRenamed('_c0','Country')
worldDF = worldDF.withColumnRenamed('_c1','Continent')
worldDF = worldDF.withColumnRenamed('_c2','CapitalCity')
worldDF = worldDF.withColumnRenamed('_c3','Population')
worldDF = worldDF.drop('Continent')
worldDF = worldDF.sort('Population',ascending=False)
worldDF = worldDF.filter(worldDF['Population']>1000000000)
worldDF.show()
worldDF.printSchema()

+--------------------+-----------+----------+
|             Country|CapitalCity|Population|
+--------------------+-----------+----------+
|China People's Re...|    Beijing|1315844000|
|               India|  New Delhi|1103371000|
+--------------------+-----------+----------+

root
 |-- Country: string (nullable = true)
 |-- CapitalCity: string (nullable = true)
 |-- Population: integer (nullable = true)

In [ ]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.getOrCreate()
worldDF = spark.read.csv('datasets/world.txt')
worldDF = worldDF.withColumnRenamed('_c0','Country')
worldDF = worldDF.withColumnRenamed('_c1','Continent')
worldDF = worldDF.withColumnRenamed('_c2','CapitalCity')
worldDF = worldDF.withColumnRenamed('_c3','Population')

worldDF = worldDF.withColumn('Population2',worldDF['Population'].cast('float'))
worldDF.printSchema()
worldDF.show()

root
 |-- Country: string (nullable = true)
 |-- Continent: string (nullable = true)
 |-- CapitalCity: string (nullable = true)
 |-- Population: string (nullable = true)
 |-- Population2: float (nullable = true)

+-------------------+-------------+----------------+----------+------------+
|            Country|    Continent|     CapitalCity|Population| Population2|
+-------------------+-------------+----------------+----------+------------+
|        Afghanistan|         Asia|           Kabul|  29863010|  2.986301E7|
|            Albania|       Europe|          Tirana|   3129678|   3129678.0|
|            Algeria|       Africa|         Algiers|  32853800|   3.28538E7|
|            Andorra|       Europe|Andorra la Vella|     67151|     67151.0|
|             Angola|       Africa|          Luanda|  15941390|  1.594139E7|
|Antigua and Barbuda|North America|      St. John's|     81479|     81479.0|
|          Argentina|South America|    Buenos Aires|  38747150| 3.8747152E7|
|            Armenia|         Asia|         Yerevan|   3016312|   3016312.0|
|          Australia|       Oceana|        Canberra|  20155130|  2.015513E7|
|            Austria|       Europe|          Vienna|   8189444|   8189444.0|
|         Azerbaijan|         Asia|            Baku|   8410801|   8410801.0|
|            Bahamas|North America|          Nassau|    323063|    323063.0|
|            Bahrain|         Asia|          Manama|    726617|    726617.0|
|         Bangladesh|         Asia|           Dhaka| 141822300|1.41822304E8|
|           Barbados|North America|      Bridgetown|    269556|    269556.0|
|            Belarus|       Europe|           Minsk|   9755106|   9755106.0|
|            Belgium|       Europe|        Brussels|  10419050|  1.041905E7|
|             Belize|North America|        Belmopan|    269736|    269736.0|
|              Benin|       Africa|         Cotonou|   8438853|   8438853.0|
|             Bhutan|         Asia|         Thimphu|   2162546|   2162546.0|
+-------------------+-------------+----------------+----------+------------+
only showing top 20 rows