In [ ]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.getOrCreate()
actorsDF = spark.read.option('header','true').option('inferSchema','true').csv('datasets/join-actors.txt')
seriesDF = spark.read.option('header','true').option('inferSchema','true').csv('datasets/series')
actorsDF.createOrReplaceTempView('actors')
seriesDF.createOrReplaceTempView('series')

joinedDF = spark.sql('select * from actors a,series s where s.movieid=a.movieid')
joinedDF.show(100)

+---+--------------------+-------+-------+------------------+
| id|                name|movieid|movieid|         moviename|
+---+--------------------+-------+-------+------------------+
|  1|           Eric Dane|      2|      2|     The Last Ship|
|  2|        Adam Baldwin|      2|      2|     The Last Ship|
|  3|     Charles Parnell|      2|      2|     The Last Ship|
|  4|         Billy Burke|      6|      6|        Revolution|
|  5|    Tracy Spiridakos|      6|      6|        Revolution|
|  6|  Giancarlo Esposito|      6|      6|        Revolution|
|  7|        Damon Wayans|      1|      1|     Lethal Weapon|
|  8|     Clayne Crawford|      1|      1|     Lethal Weapon|
|  9|      Joseph Fiennes|      5|      5|      Flashforward|
| 10|      Jack Davenport|      5|      5|      Flashforward|
| 11|    Zachary Knighton|      5|      5|      Flashforward|
| 12|        Jim Caviezel|      3|      3|Person of Interest|
| 13|     Michael Emerson|      3|      3|Person of Interest|
| 14|    Taraji P. Henson|      3|      3|Person of Interest|
| 15|      Peter Dinklage|      4|      4|   Game of Thrones|
| 16|       Emilia Clarke|      4|      4|   Game of Thrones|
| 17|       Kit Harington|      4|      4|   Game of Thrones|
| 18|Nikolaj Coster-Wa...|      4|      4|   Game of Thrones|
| 20|       Josh Holloway|      7|      7|              Lost|
| 21|    Evangeline Lilly|      7|      7|              Lost|
| 22|         Matthew Fox|      7|      7|              Lost|
+---+--------------------+-------+-------+------------------+

In [ ]:
joinedDF = spark.sql('select * from actors full outer join series on actors.movieid=series.movieid')
joinedDF.show(100)

+----+--------------------+-------+-------+------------------+
|  id|                name|movieid|movieid|         moviename|
+----+--------------------+-------+-------+------------------+
|  19|     Ahmet Demirelli|   null|   null|              null|
|   7|        Damon Wayans|      1|      1|     Lethal Weapon|
|   8|     Clayne Crawford|      1|      1|     Lethal Weapon|
|   1|           Eric Dane|      2|      2|     The Last Ship|
|   2|        Adam Baldwin|      2|      2|     The Last Ship|
|   3|     Charles Parnell|      2|      2|     The Last Ship|
|  12|        Jim Caviezel|      3|      3|Person of Interest|
|  13|     Michael Emerson|      3|      3|Person of Interest|
|  14|    Taraji P. Henson|      3|      3|Person of Interest|
|  15|      Peter Dinklage|      4|      4|   Game of Thrones|
|  16|       Emilia Clarke|      4|      4|   Game of Thrones|
|  17|       Kit Harington|      4|      4|   Game of Thrones|
|  18|Nikolaj Coster-Wa...|      4|      4|   Game of Thrones|
|   9|      Joseph Fiennes|      5|      5|      Flashforward|
|  10|      Jack Davenport|      5|      5|      Flashforward|
|  11|    Zachary Knighton|      5|      5|      Flashforward|
|   4|         Billy Burke|      6|      6|        Revolution|
|   5|    Tracy Spiridakos|      6|      6|        Revolution|
|   6|  Giancarlo Esposito|      6|      6|        Revolution|
|  20|       Josh Holloway|      7|      7|              Lost|
|  21|    Evangeline Lilly|      7|      7|              Lost|
|  22|         Matthew Fox|      7|      7|              Lost|
|null|                null|   null|      8|  Leyle ile Mecnun|
+----+--------------------+-------+-------+------------------+

In [ ]:
seriesDF.show()
spark.sql('insert into series (movieid,moviename) values (1,"Friends")')

+-------+------------------+
|movieid|         moviename|
+-------+------------------+
|      1|     Lethal Weapon|
|      2|     The Last Ship|
|      3|Person of Interest|
|      4|   Game of Thrones|
|      5|      Flashforward|
|      6|        Revolution|
|      7|              Lost|
|      8|  Leyle ile Mecnun|
+-------+------------------+

DataFrame[]

In [ ]:
seriesDF = spark.read.option('header','true').option('inferSchema','true').csv('datasets/series')
seriesDF.show()

+-------+------------------+
|movieid|         moviename|
+-------+------------------+
|      1|     Lethal Weapon|
|      2|     The Last Ship|
|      3|Person of Interest|
|      4|   Game of Thrones|
|      5|      Flashforward|
|      6|        Revolution|
|      7|              Lost|
|      8|  Leyle ile Mecnun|
|      1|           Friends|
+-------+------------------+